import { HOME_STACK_ROUTES, AUTH_ROUTES, WEBVIEW_STACK_ROUTES, DRAWER_ROUTES, ROOT_ROUTES } from './route-keys';

// Route structure for use in navigation
export const ROUTES = {
  HOME: {
    MAIN: HOME_STACK_ROUTES.MAIN,
  },
  WEBVIEW: {
    MAIN: WEBVIEW_STACK_ROUTES.MAIN,
  },
  AUTH: {
    LOGIN: AUTH_ROUTES.LOGIN,
    REGISTER: AUTH_ROUTES.REGISTER,
    FORGOT_PASSWORD: AUTH_ROUTES.FORGOT_PASSWORD,
  },
  DRAWER: {
    HOME: DRAWER_ROUTES.HOME,
    WEBVIEW: DRAWER_ROUTES.WEBVIEW,
    SETTING: DRAWER_ROUTES.SETTING,
  },
  ROOT: {
    MAIN: ROOT_ROUTES.MAIN,
    AUTH: ROOT_ROUTES.AUTH,
    SETTING: ROOT_ROUTES.SETTING,
    SPLASH: ROOT_ROUTES.SPLASH,
  },
};
